=== Figuier7/alombredufiguier-bible-data/schemas/interlinear-book.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Figuier Interlinear Book",
  "type": "object",
  "required": [
    "book",
    "code",
    "chapters"
  ],
  "properties": {
    "book": {
      "type": "string"
    },
    "code": {
      "type": "string"
    },
    "name_fr": {
      "type": "string"
    },
    "chapters": {
      "type": "object"
    }
  },
  "additionalProperties": true
}

=== Figuier7/alombredufiguier-bible-data/data/interlinear/at/30-Amos.json
{"book":"Amos","code":"30","name_fr":"Amos","chapters":{"1":{"1":[{"t":"דִּבְרֵ֣י","s":"H1697","m":"HNcmpc","x":"dâbâr","g":"mot"},{"t":"עָמ֔וֹס","s":"H5986","m":"HNp","x":"ʻÂmôwç","g":"Amos"},{"t":"אֲשֶׁר","s":"H834","m":"HTr","x":"ʼăsher","g":"que"},{"t":"הָיָ֥ה","s":"H1961","m":"HVqp3ms","x":"hâyâh","g":"être"},{"t":"בַ/נֹּקְדִ֖ים","s":"H5349","m":"HRd/Ncmpa","x":"nôqêd","g":"gardien"},{"t":"מִ/תְּק֑וֹעַ","s":"H8620","m":"HR/Np","x":"Tᵉqôwaʻ","g":"Tekoa"},{"t":"אֲשֶׁר֩","s":"H834","m":"HTr","x":"ʼăsher","g":"que"},{"t":"חָזָ֨ה","s":"H2372","m":"HVqp3ms","x":"châzâh","g":"regarder"},{"t":"עַל","s":"H5921","m":"HR","x":"ʻal","g":"au-dessus"},{"t":"יִשְׂרָאֵ֜ל","s":"H3478","m":"HNp","x":"Yisrâʼêl","g":"Israël"},{"t":"בִּ/ימֵ֣י","s":"H3117","m":"HR/Ncmpc","x":"yôwm","g":"jour"},{"t":"עֻזִיָּ֣ה","s":"H5818","m":"HNp","x":"ʻUzzîyâh","g":"Uzziyah"},{"t":"מֶֽלֶךְ","s":"H4428","m":"HNcmsc","x":"melek","g":"roi"},{"t":"יְהוּדָ֗ה","s":"H3063","m":"HNp","x":"Yᵉhûwdâh","g":"Yehudah"},{"t":"וּ/בִ/ימֵ֞י","s":"H3117","m":"HC/R/Ncmpc","x":"yôwm","g":"jour"},{"t":"יָרָבְעָ֤ם","s":"H3379","m":"HNp","x":"Yârobʻâm","g":"Yarobam"},{"t":"בֶּן","s":"H1121","m":"HNcmsc","x":"bên","g":"fils"},{"t":"יוֹאָשׁ֙","s":"H3101","m":"HNp","x":"Yôwʼâsh","g":"Yôwʼâsh"},{"t":"מֶ֣לֶךְ","s":"H4428","m":"HNcmsc","x":"melek","g":"roi"},{"t":"יִשְׂרָאֵ֔ל","s":"H3478","m":"HNp","x":"Yisrâʼêl","g":"Israël"},{"t":"שְׁנָתַ֖יִם","s":"H8141","m":"HNcfda","x":"shâneh","g":"année"},{"t":"לִ/פְנֵ֥י","s":"H6440","m":"HR/Ncbpc","x":"pânîym","g":"visage"},{"t":"הָ/רָֽעַשׁ","s":"H7494","m":"HTd/Ncmsa","x":"raʻash","g":"vibration"}],"2":[{"t":"וַ/יֹּאמַ֓ר","s":"H559","m":"HC/Vqw3ms","x":"ʼâmar","g":"dire"},{"t":"יְהוָה֙","s":"H3068","m":"HNp","x":"Yᵉhôvâh","g":"YHWH"},{"t":"מִ/צִיּ֣וֹן","s":"H6726","m":"HR/Np","x":"Tsîyôwn","g":"Tsiyon"},{"t":"יִשְׁאָ֔ג","s":"H7580","m":"HVqi3ms","x":"shâʼag","g":"rugir"},{"t":"וּ/מִ/ירוּשָׁלִַ֖ם","s":"H3389","m":"HC/R/Np","x":"Yᵉrûwshâlaim","g":"Yerushalaim"},{"t":"יִתֵּ֣ן","s":"H5414","m":"HVqi3ms","x":"nâthan","g":"donner"},{"t":"קוֹל֑/וֹ","s":"H6963","m":"HNcmsc/Sp3ms","x":"qôwl","g":"voix"},{"t":"וְ/אָֽבְלוּ֙","s":"H56","m":"HC/Vqp3cp","x":"ʼâbal","g":"se lamenter"},{"t":"נְא֣וֹת","s":"H4999","m":"HNcfpc","x":"nâʼâh","g":"pâturage"},{"t":"הָ/רֹעִ֔ים","s":"H7462","m":"HTd/Vqrmpa","x":"rāʿâ","g":"pâturer","sa":"B"},{"t":"וְ/יָבֵ֖שׁ","s":"H3001","m":"HC/Vqp3ms","x":"yâbêsh","g":"honteux"},{"t":"רֹ֥אשׁ","s":"H7218","m":"HNcmsc","x":"rôʼsh","g":"tête"},{"t":"הַ/כַּרְמֶֽל","s":"H3760","m":"HTd/Np","x":"Karmel","g":"Karmel"}],"3":[{"t":"כֹּ֚ה","s":"H3541","m":"HD","x":"kôh","g":"comme ceci"},{"t":"אָמַ֣ר","s":"H559","m":"HVqp3ms","x":"ʼâmar","g":"dire"},{"t":"יְהוָ֔ה","s":"H3068","m":"HNp","x":"Yᵉhôvâh","g":"YHWH"},{"t":"עַל","s":"H5921","m":"HR","x":"ʻal","g":"au-dessus"},{"t":"שְׁלֹשָׁה֙","s":"H7969","m":"HAcmsa","x":"shâlôwsh","g":"trois"},{"t":"פִּשְׁעֵ֣י","s":"H6588","m":"HNcmpc","x":"peshaʻ","g":"révolte"},{"t":"דַמֶּ֔שֶׂק","s":"H1834","m":"HNp","x":"Dammeseq","g":"Damas"},{"t":"וְ/עַל","s":"H5921","m":"HC/R","x":"ʻal","g":"au-dessus"},{"t":"אַרְבָּעָ֖ה","s":"H702","m":"HAcmsa","x":"ʼarbaʻ","g":"quatre"},{"t":"לֹ֣א","s":"H3808","m":"HTn","x":"lôʼ","g":"non"},{"t":"אֲשִׁיבֶ֑/נּוּ","s":"H7725","m":"HVhi1cs/Sp3ms","x":"shûwb","g":"retourner"},{"t":"עַל","s":"H5921","m":"HR","x":"ʻal","g":"au-dessus"},{"t":"דּוּשָׁ֛/ם","s":"H1758","m":"HVqc/Sp3mp","x":"dûwsh","g":"piétiner"},{"t":"בַּ/חֲרֻצ֥וֹת","s":"H2742","m":"HR/Ncmpc","x":"chărûwts","g":"incisé"},{"t":"הַ/בַּרְזֶ֖ל","s":"H1270","m":"HTd/Ncmsa","x":"barzel","g":"fer"},{"t":"אֶת","s":"H853","m":"HTo","x":"ʼêth","g":"[obj]"},{"t":"הַ/גִּלְעָֽד","s":"H1568","m":"HTd/Np","x":"Gilʻâd","g":"Gilad"}],"4":[{"t":"וְ/שִׁלַּ֥חְתִּי","s":"H7971","m":"HC/Vpq1cs","x":"shâlach","g":"envoyer"},{"t":"אֵ֖שׁ","s":"H784","m":"HNcbsa","x":"ʼêsh","g":"feu"},{"t":"בְּ/בֵ֣ית","s":"H1004","m":"HR/Ncmsc","x":"bayith","g":"maison"},{"t":"חֲזָאֵ֑ל","s":"H2371","m":"HNp","x":"Chăzâʼêl","g":"Chazael"},{"t":"וְ/אָכְלָ֖ה","s":"H398","m":"HC/Vqq3fs","x":"ʼâkal","g":"manger"},{"t":"אַרְמְנ֥וֹת","s":"H759","m":"HNcmpc","x":"ʼarmôwn","g":"citadelle"},{"t":"בֶּן","s":"H1130","m":"HNp","x":"Ben-Hădad","g":"Ben-Hadad"},{"t":"הֲדָֽד","s":"H1130","m":"HNp","x":"Ben-Hădad","g":"Ben-Hadad"}],"5":[{"t":"וְ/שָֽׁבַרְתִּי֙","s":"H7665","m":"HC/Vqq1cs","x":"shâbar","g":"éclater"},{"t":"בְּרִ֣יחַ","s":"H1280","m":"HNcmsc","x":"bᵉrîyach","g":"verrou"},{"t":"דַּמֶּ֔שֶׂק","s":"H1834","m":"HNp","x":"Dammeseq","g":"Damas"},{"t":"וְ/הִכְרַתִּ֤י","s":"H3772","m":"HC/Vhq1cs","x":"kârath","g":"retrancher"},{"t":"יוֹשֵׁב֙","s":"H3427","m":"HVqrmsa","x":"yâshab","g":"demeurer"},{"t":"מִ/בִּקְעַת","s":"H1237","m":"HR/Np","x":"biqʻâh","g":"fente"},{"t":"אָ֔וֶן","s":"H206","m":"HNp","x":"ʼÂven","g":"Aven"},{"t":"וְ/תוֹמֵ֥ךְ","s":"H8551","m":"HC/Vqrmsc","x":"tâmak","g":"soutenir"},{"t":"שֵׁ֖בֶט","s":"H7626","m":"HNcmsa","x":"shêbeṭ","g":"rejeton"},{"t":"מִ/בֵּ֣ית","s":"H1004","m":"HR/Np","x":"bayith","g":"maison"},{"t":"עֶ֑דֶן","s":"H5730","m":"HNp","x":"ʻêden","g":"plaisir"},{"t":"וְ/גָל֧וּ","s":"H1540","m":"HC/Vqq3cp","x":"gâlâh","g":"dénuder"},{"t":"עַם","s":"H5971","m":"HNcmsc","x":"ʻam","g":"peuple"},{"t":"אֲרָ֛ם","s":"H758","m":"HNp","x":"ʼĂrâm","g":"Aram"},{"t":"קִ֖ירָ/ה","s":"H7024","m":"HNp/Sd","x":"Qîyr","g":"Kir"},{"t":"אָמַ֥ר","s":"H559","m":"HVqp3ms","x":"ʼâmar","g":"dire"},{"t":"יְהוָֽה","s":"H3068","m":"HNp","x":"Yᵉhôvâh","g":"YHWH"}],"6":[{"t":"כֹּ֚ה","s":"H3541","m":"HD","x":"kôh","g":"comme ceci"},{"t":"אָמַ֣ר","s":"H559","m":"HVqp3ms","x":"ʼâmar","g":"dire"},{"t":"יְהוָ֔ה","s":"H3068","m":"HNp","x":"Yᵉhôvâh","g":"YHWH"},{"t":"עַל","s":"H5921","m":"HR","x":"ʻal","g":"au-dessus"},{"t":"שְׁלֹשָׁה֙","s":"H7969","m":"HAcmsa","x":"shâlôwsh","g":"trois"},{"t":"פִּשְׁעֵ֣י","s":"H6588","m":"HNcmpc","x":"peshaʻ","g":"révolte"},{"t":"עַזָּ֔ה","s":"H5804","m":"HNp","x":"ʻAzzâh","g":"Azzah"},{"t":"וְ/עַל","s":"H5921","m":"HC/R","x":"ʻal","g":"au-dessus"},{"t":"אַרְבָּעָ֖ה","s":"H702","m":"HAcmsa","x":"ʼarbaʻ","g":"quatre"},{"t":"לֹ֣א","s":"H3808","m":"HTn","x":"lôʼ","g":"non"},{"t":"אֲשִׁיבֶ֑/נּוּ","s":"H7725","m":"HVhi1cs/Sp3ms","x":"shûwb","g":"retourner"},{"t":"עַל","s":"H5921","m":"HR","x":"ʻal","g":"au-dessus"},{"t":"הַגְלוֹתָ֛/ם","s":"H1540","m":"HVhc/Sp3mp","x":"gâlâh","g":"dénuder"},{"t":"גָּל֥וּת","s":"H1546","m":"HNcfsa","x":"gâlûwth","g":"captivité"},{"t":"שְׁלֵמָ֖ה","s":"H8003","m":"HAafsa","x":"shâlêm","g":"complet"},{"t":"לְ/הַסְגִּ֥יר","s":"H5462","m":"HR/Vhc","x":"çâgar","g":"fermer"},{"t":"לֶ/אֱדֽוֹם","s":"H123","m":"HR/Np","x":"ʼĔdôm","g":"Édom"}],"7":[{"t":"וְ/שִׁלַּ֥חְתִּי","s":"H7971","m":"HC/Vpq1cs","x":"shâlach","g":"envoyer"},{"t":"אֵ֖שׁ","s":"H784","m":"HNcbsa","x":"ʼêsh","g":"feu"},{"t":"בְּ/חוֹמַ֣ת","s":"H2346","m":"HR/Ncfsc","x":"chôwmâh","g":"mur"},{"t":"עַזָּ֑ה","s":"H5804","m":"HNp","x":"ʻAzzâh","g":"Azzah"},{"t":"וְ/אָכְלָ֖ה","s":"H398","m":"HC/Vqq3fs","x":"ʼâkal","g":"manger"},{"t":"אַרְמְנֹתֶֽי/הָ","s":"H759","m":"HNcmpc/Sp3fs","x":"ʼarmôwn","g":"citadelle"}],"8":[{"t":"וְ/הִכְרַתִּ֤י","s":"H3772","m":"HC/Vhq1cs","x":"kârath","g":"retrancher"},{"t":"יוֹשֵׁב֙","s":"H3427","m":"HVqrmsa","x":"yâshab","g":"demeurer"},{"t":"מֵֽ/אַשְׁדּ֔וֹד","s":"H795","m":"HR/Np","x":"ʼAshdôwd","g":"Ashdod"},{"t":"וְ/תוֹמֵ֥ךְ","s":"H8551","m":"HC/Vqrmsc","x":"tâmak","g":"soutenir"},{"t":"שֵׁ֖בֶט","s":"H7626","m":"HNcmsa","x":"shêbeṭ","g":"rejeton"},{"t":"מֵֽ/אַשְׁקְל֑וֹן","s":"H831","m":"HR/Np","x":"ʼAshqᵉlôwn","g":"Ashkelon"},{"t":"וַ/הֲשִׁיב֨וֹתִי","s":"H7725","m":"HC/Vhq1cs","x":"shûwb","g":"retourner"},{"t":"יָדִ֜/י","s":"H3027","m":"HNcbsc/Sp1cs","x":"yâd","g":"main"},{"t":"עַל","s":"H5921","m":"HR","x":"ʻal","g":"au-dessus"},{"t":"עֶקְר֗וֹן","s":"H6138","m":"HNp","x":"ʻEqrôwn","g":"Ekron"},{"t":"וְ/אָֽבְדוּ֙","s":"H6","m":"HC/Vqq3cp","x":"ʼâbad","g":"errer"},{"t":"שְׁאֵרִ֣ית","s":"H7611","m":"HNcfsc","x":"shᵉʼêrîyth","g":"reste"},{"t":"פְּלִשְׁתִּ֔ים","s":"H6430","m":"HNgmpa","x":"Pᵉlishtîy","g":"Pelishtite"},{"t":"אָמַ֖ר","s":"H559","m":"HVqp3ms","x":"ʼâmar","g":"dire"},{"t":"אֲדֹנָ֥/י","s":"H136","m":"HNcmpc/Sp1cs","x":"ʼĂdônây","g":"Seigneur"},{"t":"יְהוִֽה","s":"H3069","m":"HNp","x":"Yᵉhôvih","g":"YHWH"}],"9":[{"t":"כֹּ֚ה","s":"H3541","m":"HD","x":"kôh","g":"comme ceci"},{"t":"אָמַ֣ר","s":"H559","m":"HVqp3ms","x":"ʼâmar","g":"dire"},{"t":"יְהוָ֔ה","s":"H3068","m":"HNp","x":"Yᵉhôvâh","g":"YHWH"},{"t":"עַל","s":"H5921","m":"HR","x":"ʻal","g":"au-dessus"},{"t":"שְׁלֹשָׁה֙","s":"H7969","m":"HAcmsa","x":"shâlôwsh","g":"trois"},{"t":"פִּשְׁעֵי","s":"H6588","m":"HNcmpc","x":"peshaʻ","g":"révolte"},{"t":"צֹ֔ר","s":"H6865","m":"HNp","x":"Tsôr","g":"Tsor"},{"t":"וְ/עַל","s":"H5921","m":"HC/R","x":"ʻal","g":"au-dessus"},{"t":"אַרְבָּעָ֖ה","s":"H702","m":"HAcmsa","x":"ʼarbaʻ","g":"quatre"},{"t":"לֹ֣א","s":"H3808","m":"HTn","x":"lôʼ","g":"non"},{"t":"אֲשִׁיבֶ֑/נּוּ","s":"H7725","m":"HVhi1cs/Sp3ms","x":"shûwb","g":"retourner"},{"t":"עַֽל","s":"H5921","m":"HR","x":"ʻal","g":"au-dessus"},{"t":"הַסְגִּירָ֞/ם","s":"H5462","m":"HVhc/Sp3mp","x":"çâgar","g":"fermer"},{"t":"גָּל֤וּת","s":"H1546","m":"HNcfsa","x":"gâlûwth","g":"captivité"},{"t":"שְׁלֵמָה֙","s":"H8003","m":"HAafsa","x":"shâlêm","g":"complet"},{"t":"לֶ/אֱד֔וֹם","s":"H123","m":"HR/Np","x":"ʼĔdôm","g":"Édom"},{"t":"וְ/לֹ֥א","s":"H3808","m":"HC/Tn","x":"lôʼ","g":"non"},{"t":"זָכְר֖וּ","s":"H2142","m":"HVqp3cp","x":"zâkar","g":"marquer"},{"t":"בְּרִ֥ית","s":"H1285","m":"HNcfsc","x":"bᵉrîyth","g":"alliance"},{"t":"אַחִֽים","s":"H251","m":"HNcmpa","x":"ʼâch","g":"frère"}],"10":[{"t":"וְ/שִׁלַּ֥חְתִּי","s":"H7971","m":"HC/Vpq1cs","x":"shâlach","g":"envoyer"},{"t":"אֵ֖שׁ","s":"H784","m":"HNcbsa","x":"ʼêsh","g":"feu"},{"t":"בְּ/ח֣וֹמַת","s":"H2346","m":"HR/Ncfsc","x":"chôwmâh","g":"mur"},{"t":"צֹ֑ר","s":"H6865","m":"HNp","x":"Tsôr","g":"Tsor"},{"t":"וְ/אָכְלָ֖ה","s":"H398","m":"HC/Vqq3fs","x":"ʼâkal","g":"manger"},{"t":"אַרְמְנֹתֶֽי/הָ","s":"H759","m":"HNcmpc/Sp3fs","x":"ʼarmôwn","g":"citadelle"}],"11":[{"t":"כֹּ֚ה","s":"H3541","m":"HD","x":"kôh","g":"comme ceci"},{"t":"אָמַ֣ר"
